services:
  - type: web
    name: chess-arena-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: chess-arena-api
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CLIENT_URL
        fromService:
          name: chess-arena-client
          type: web
          property: url
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
